#!/bin/bash
documodel_include="include 'documodel.conf'"
postgres_dir=$(dmdk config get postgresql.data_dir 2>/dev/null)

if ! grep -Fxq "$documodel_include" "$postgres_dir"/postgresql.conf; then
  echo "$documodel_include" >> "$postgres_dir"/postgresql.conf
fi

if [ ! -f "$postgres_dir/documodel.conf" ]; then
  cat <<EOF > "$postgres_dir"/documodel.conf
random_page_cost = '1'
work_mem = '16MB'
maintenance_work_mem = '64MB'
shared_buffers = '256MB'
EOF
fi
