---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - ruby
  fixme:
    enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - support/**/*
  - bin/*
  - "**.rb"
exclude_paths:
- "**/vendor/**/*"
- documodel/
- documodel-elasticsearch-indexer
- documodel-shell/
- documodel-workhorse/
- reposities/
- postgresql/
- redis/
