apiVersion: v1
kind: Service
metadata:
  name: dmdk
  labels:
    app: dmdk
spec:
  ports:
    - port: 3000
  selector:
    app: dmdk
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmdk
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dmdk
  template:
    metadata:
      labels:
        app: dmdk
    spec:
      containers:
        - name: dmdk
          image: registry.gitlab.com/gitlab-org/gitlab-development-kit
          imagePullPolicy: Always
          ports:
          - name: dmdk
            containerPort: 3000
          command:
            - /bin/bash
            - -c
            - >
              source /home/dmdk/.bash_profile;
              gem install gitlab-development-kit;
              cd /home/dmdk;
              dmdk init;
              cd gitlab-development-kit;
              echo 'hostname: 0.0.0.0' > dmdk.yml;
              dmdk install;
              dmdk start;
              dmdk tail
